Script


so what are vectors
vector is a mathematical quantity that has both magnitude and direction 

geometrically 
it is represented as an arrow, 
starting from the origin and pointing to any point on this N dimensional space

n=2 in case 

position vector. 
what is a position vector? 
which tells you the relative position of a point w.r.t a reference point usually the origin 

how to write vector as a column matrix 

vector scaling 

